NAME = Bureaucrat
CC = c++
CFLAGS= -Wall -Wextra -Werror -std=c++98

SRC = Bureaucrat.cpp AForm.cpp RobotomyRequestForm.cpp ShrubberyCreationForm.cpp PresidentialPardonForm.cpp  main.cpp

all:
	$(CC) $(CFLAGS) $(SRC) -o $(NAME)

fclean:
	rm -rf $(NAME)

re:
	fclean all